[package]
name = "atim"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
tokio = { workspace = true, features = ["full"] }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
clap = { version = "4", features = ["derive"] }
libc = { workspace = true }
atim-core = { path = "../atim-core" }
atim-tmux = { path = "../atim-tmux" }
atim-parser = { path = "../atim-parser" }
atim-state = { path = "../atim-state" }
atim-im = { path = "../atim-im" }
atim-queue = { path = "../atim-queue" }
atim-monitor = { path = "../atim-monitor" }
reqwest = { version = "0.12", features = ["json", "multipart"] }
dotenvy = "0.15"
