[package]
name = "atim"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true

[dependencies]
tokio = { workspace = true, features = ["full"] }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
clap = { version = "4", features = ["derive"] }
libc = { workspace = true }
atim-core = { path = "../atim-core", version = "0.1.0" }
atim-tmux = { path = "../atim-tmux", version = "0.1.0" }
atim-parser = { path = "../atim-parser", version = "0.1.0" }
atim-state = { path = "../atim-state", version = "0.1.0" }
atim-im = { path = "../atim-im", version = "0.1.0" }
atim-queue = { path = "../atim-queue", version = "0.1.0" }
atim-monitor = { path = "../atim-monitor", version = "0.1.0" }
reqwest = { version = "0.12", default-features = false, features = ["json", "multipart", "rustls-tls"] }
dotenvy = "0.15"
