[package]
name = "atim-state"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true

[dependencies]
tokio = { workspace = true, features = ["fs"] }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
libc = { workspace = true }
rusqlite = { workspace = true }
chrono = { workspace = true }
toml = { workspace = true }
atim-core = { path = "../atim-core", version = "0.3" }
