[package]
name = "atim-tmux"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true

[dependencies]
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
atim-core = { path = "../atim-core", version = "0.4" }
image = { version = "0.25", default-features = false, features = ["png"] }
imageproc = { version = "0.27", default-features = false, features = ["text"] }
ab_glyph = "0.2"
regex = "1"

[target.'cfg(windows)'.dependencies]
portable-pty = "0.9"
